apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: webhook-source
spec:
  service:
    ports:
      - port: 12000
        targetPort: 12000
  webhook:
    devops-toolkit:
      port: "12000"
      endpoint: /webhook01
      method: POST